### ISSUE TITLE
Issues when using printf 

### ISSUE THREAD

**Issue by 343GuiltySpark-04** [V01D-NULL/limine-terminal-port#6] opened 2022-10-22 22:50 UTC
when using printf after calling term_write() i get no further output to the screen. same if term_write() is not used in the function at all but its just a blank screen and a cursor.

for example 

```
void main(){

//assuming proper setup done above

printf(arg, arg);

term_write(arg, arg);

printf(arg, arg);
}
```
will give me the output of the first printf call and the term_write() call but not the second printf.

is this by design, a bug or me missing something?

any help or insight would be appreciated @V01D-NULL or @ilobilo

**Comment by 343GuiltySpark-04** [comment] 2022-10-22 22:53
i should note that using term_raw_putchar() rather then term_putchar() seems to work right it albeit with the obvious lack of formatting

**Comment by V01D-NULL** [comment] 2022-10-23 18:36
Your printf function is probably broken.
Either that or your memory allocator for the setup.

I'd need to see a way to repro.

**Comment by 343GuiltySpark-04** [comment] 2022-10-23 19:43
yeah i was thinking it might be that i didn't use memset after allocation (mostly on the advice of the guy who helped make my paging etc code) so i'm going to see if that fixes it 
[https://github.com/343GuiltySpark-04/VoyagerOS64/tree/terminal_troubleshoot](url)

**Comment by 343GuiltySpark-04** [comment] 2022-10-23 19:48
i'm just not sure what to put as the target for the memset call i.e

memset(target, 0, size);

just don't know what target should be

**Comment by 343GuiltySpark-04** [comment] 2022-10-23 20:54
![Screenshot from 2022-10-23 16-53-39](https://user-images.githubusercontent.com/69496138/197417838-ddfff375-12a4-4c8d-9bac-65b492052d48.png)
here as an example, should print "Kernel Loaded" again after the name and version.

**Comment by 343GuiltySpark-04** [comment] 2022-10-23 21:25
additionally here's the printf lib im using 
[https://github.com/mpaland/printf](url)

lemme know what you find out @V01D-NULL

**Comment by V01D-NULL** [comment] 2022-10-23 21:46
> i'm just not sure what to put as the target for the memset call i.e
> 
> memset(target, 0, size);
> 
> just don't know what target should be

Uh.... It's in the Readme my guy.
void*

**Comment by 343GuiltySpark-04** [comment] 2022-10-23 21:49
> Uh.... It's in the Readme my guy.
void*

i meant for the call in void *allocmem(size)

**Comment by 343GuiltySpark-04** [comment] 2022-10-23 21:54
because the comments for that say 
> memset() to zero

which i never did so im wondering what the target param is for it as i think that might be the cause of my problem

**Comment by V01D-NULL** [comment] 2022-10-23 21:56
target param?
Well you obviously want to zero out the allocated memory lol

**Comment by V01D-NULL** [comment] 2022-10-23 21:56
And that's not your problem, this is: https://github.com/343GuiltySpark-04/VoyagerOS64/blob/terminal_troubleshoot/src/putchar.c#L26

Can't use the terminal to write characters if you don't call any functions for that to happen

**Comment by 343GuiltySpark-04** [comment] 2022-10-23 21:57
> target param? Well you obviously want to zero out the allocated memory lol

exactly but memset takes three args i know the second has to be `0` and the third `size` but i don't know what to put for the first one

**Comment by V01D-NULL** [comment] 2022-10-23 22:01
Lmao dude think about it/
`void *memset(void *dest, int ch, size_t n)`

We know what `ch` and `n` are for.
`dest` is the start of the memory range we want to set to `ch`

What does alloc_mem return? 
memory.

What's your first parameter for memset...?

**Comment by 343GuiltySpark-04** [comment] 2022-10-23 22:04
so something like 
`memset(malloc(size), 0, size);`
?

**Comment by V01D-NULL** [comment] 2022-10-23 22:06
You need to learn C my guy. Obviously you shouldn't do that, how else are you gonna return the memory you allocated and zeroed out?

Store it in a variable, memset it and return it.

**Comment by 343GuiltySpark-04** [comment] 2022-10-23 22:14
was my first thought but didn't think it would work. i'll let you know if it resolves the issue though

**Comment by 343GuiltySpark-04** [comment] 2022-10-23 22:20
no change unfortunately

**Comment by V01D-NULL** [comment] 2022-10-23 22:50
I already told you what the issue is here

> And that's not your problem, this is: https://github.com/343GuiltySpark-04/VoyagerOS64/blob/terminal_troubleshoot/src/putchar.c#L26
> 
> Can't use the terminal to write characters if you don't call any functions for that to happen

**Comment by 343GuiltySpark-04** [comment] 2022-10-23 23:04
I had that commented out while testing the interrupts, but yes when it was uncommented it was having the aforementioned problems. my bad

**Comment by V01D-NULL** [comment] 2022-10-24 01:51
I suggest you step through it with a debugger.

Figure out what it's doing.

**Comment by 343GuiltySpark-04** [comment] 2022-10-24 01:54
yeah i'm planning on that in the morning, any pointers (no pun intended) on what values i should keep a close eye on?

**Comment by V01D-NULL** [comment] 2022-10-24 14:51
term_t. 

You should also just move terminal initialization into your terminal source file

**Comment by 343GuiltySpark-04** [comment] 2022-10-24 15:49
ah i see the issue, for some reason `term_backend` is defaulting back to `NOT_READY`

**Comment by 343GuiltySpark-04** [comment] 2022-10-24 15:50
could GCC be thinking the object is no longer used and optimizing it out possibly?

**Comment by 343GuiltySpark-04** [comment] 2022-10-24 16:10
hmm or not, it seems that it remains ready.

**Comment by V01D-NULL** [comment] 2022-11-04 18:15
Well... whatever it is, it's most likely not the terminal.
So unless you have any proof that it's caused by this port, I will close this issue in a few hours.

**Comment by V01D-NULL** [comment] 2022-11-16 01:21
I forgor to close it 💀

**Closed as completed** 2022-11-16 01:21 UTC
